default_settings: 
behaviors:
  FootBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 0
      buffer_size: 0
      learning_rate: 0
      beta: 0
      epsilon: 0
      lambd: 0
      num_epoch: 6
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
      memory: 
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 5
          vis_encode_type: simple
          memory: 
          goal_conditioning_type: hyper
          deterministic: false
    init_path: 
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 10000
    time_horizon: 64
    summary_freq: 5000
    threaded: false
    self_play: 
    behavioral_cloning: 
env_settings:
  env_path: 
  env_args: 
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: 
checkpoint_settings:
  run_id: FootBall
  initialize_from: 
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: 
debug: false
